// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Smart_Comment
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSmart_CommentPackageString = "cf31a015-b474-422c-aae2-3dd1d534bccc";
        public static Guid guidSmart_CommentPackage = new Guid(guidSmart_CommentPackageString);

        public const string guidSmart_CommentPackageCmdSetString = "5c41565b-5ed3-40e1-b738-e8f46a17d54f";
        public static Guid guidSmart_CommentPackageCmdSet = new Guid(guidSmart_CommentPackageCmdSetString);

        public const string guidImagesString = "eeefe992-b4e3-4c8e-a87c-e9bb5b6d72fd";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "723f2f10-f433-4ca6-89e9-5d8dc550d9d2";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidImages2String = "3af3e02c-98b2-4f49-941f-c3360493404f";
        public static Guid guidImages2 = new Guid(guidImages2String);

        public const string guidSmart_CommentPackageCmdSet1String = "39e1621e-03d0-496f-886f-79d1d6168ff7";
        public static Guid guidSmart_CommentPackageCmdSet1 = new Guid(guidSmart_CommentPackageCmdSet1String);

        public const string guidImages3String = "85d8a1d3-67e7-4d65-a694-b3e5a35e1326";
        public static Guid guidImages3 = new Guid(guidImages3String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidSCInvisible = 0x0100;
    }
}